version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: kittygram_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    container_name: kittygram_backend
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    container_name: kittygram_frontend
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    container_name: kittygram_gataway
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media/
    ports:
      - 9000:80
